/**
 * JSON Schema Index File
 * generated by Setaria
 */
import Claim from "./claim.json";
import Config from "./config.json";
import Cac from "./cac.json";
import Fund from "./fund.json";
import Demo from "./demo.json";

export default {
  Claim,
  Config,
  Cac,
  Fund,
  Demo,
};
